/*
* Copyright (c) 2018 CD Projekt Red. All Rights Reserved.
*/

#include "build.h"
#include "jobSystem.h"
#include "jobDispatcherInitParam.h"
#include "jobDispatcher.h"
#include "jobDebugger.h"
#include "jobDecl.h"
#include "jobCounter.h"
#include "jobShim.h"
#include "jobMemoryPools.h"

#ifndef RED_CONFIGURATION_FINAL
# define USE_DEBUG_DUMP_STACKTRACES
#endif

namespace job
{

extern void InitializeJobMemoryPools();

namespace prv
{
	extern thread_local Uint32 g_tls_DispatcherThreadIndex;
	extern thread_local Bool g_tls_IsDispatcherThread;
	extern Dispatcher* gDispatcher;
}

void Initialize( const InitParam& setup )
{
	RED_FATAL_ASSERT( !prv::gDispatcher );

	// assign thread index for the main thread
	prv::g_tls_DispatcherThreadIndex = 0;

	InitializeJobMemoryPools(); // #tbd: some better place to put this, but red* modules don't get their init autogenerated
	prv::gDispatcher = RED_NEW( prv::Dispatcher )( setup );
}

void Shutdown()
{
	RED_FATAL_ASSERT( prv::gDispatcher );
	RED_DELETE( prv::gDispatcher );
	prv::gDispatcher = nullptr;
	ShutdownJobMemoryPools();
}

Uint32 GetNumDispatcherThreads(Bool includeCore7)
{
	RED_FATAL_ASSERT( prv::gDispatcher );
	return prv::gDispatcher->GetNumDispatcherThreads(includeCore7);
}

Uint32 GetDispatcherThreadIndex()
{
	return prv::g_tls_DispatcherThreadIndex;
}

Uint32 GetApproximateQueueDepth( Priority priority )
{
	return prv::gDispatcher
		? prv::gDispatcher->GetApproximateQueueDepth( priority )
		: 0;
}

void DumpToLog()
{
}

StackTraceHandle DebugTraceCall()
{
	RED_FATAL_ASSERT( prv::gDispatcher );
	if ( RED_UNLIKELY( prv::gDispatcher->GetDebugger() != nullptr ) )
	{
		return StackTraceHandle( prv::gDispatcher->GetDebugger()->TraceCall() );
	}
	return StackTraceHandle();
}

void FatalAssertIfDispatcherThread()
{
	RED_FATAL_ASSERT(!prv::g_tls_IsDispatcherThread, "Somebody decided that you shouldn't do whatever it is you're doing on a job thread. Maybe I/O.");
}

} // job

namespace io
{
	thread_local EAsyncPriority t_ioPriority = EAsyncPriority::eAsyncPriority_INVALID;

	void SetThreadLocalIOPriority( EAsyncPriority prio ) 
	{ 
		t_ioPriority = prio; 
	}

	EAsyncPriority GetThreadLocalIOPriority() 
	{ 
		return t_ioPriority; 
	}
} // io

