#pragma once

// This is an inline/SIMD-heavy library. The boundary deliberately exposes the
// complete adapted image under Vanguard ownership instead of placing a
// function-call wrapper in every arithmetic operation.
#include "../../../adapted/include/redMathPublic.h"

#include "../../../adapted/include/box.h"
#include "../../../adapted/include/cutCone.h"
#include "../../../adapted/include/cylinder.h"
#include "../../../adapted/include/fixedCapsule.h"
#include "../../../adapted/include/fixedPoint.h"
#include "../../../adapted/include/float16compressor.h"
#include "../../../adapted/include/half.h"
#include "../../../adapted/include/interpolation.h"
#include "../../../adapted/include/mathUtils.h"
#include "../../../adapted/include/matrixDouble.h"
#include "../../../adapted/include/orientedBox.h"
#include "../../../adapted/include/perlinNoise.h"
#include "../../../adapted/include/plane.h"
#include "../../../adapted/include/point.h"
#include "../../../adapted/include/point3D.h"
#include "../../../adapted/include/quad.h"
#include "../../../adapted/include/random.h"
#include "../../../adapted/include/rect.h"
#include "../../../adapted/include/rectf.h"
#include "../../../adapted/include/segment.h"
#include "../../../adapted/include/simdBox.h"
#include "../../../adapted/include/simdComparisonResult.h"
#include "../../../adapted/include/simdQSTransform.h"
#include "../../../adapted/include/simdQuad.h"
#include "../../../adapted/include/simdScalar.h"
#include "../../../adapted/include/simdVector4.h"
#include "../../../adapted/include/simdVectorArithmetic.h"
#include "../../../adapted/include/simdVectorFunctions.h"
#include "../../../adapted/include/sphere.h"
#include "../../../adapted/include/tetrahedron.h"
#include "../../../adapted/include/worldPosition.h"
#include "../../../adapted/include/worldTransform.h"
