/**
* Copyright (c) 2016 CDProjekt Red, Inc. All Rights Reserved.
*/

#pragma once

#include "redThreadsAtomic.h"
#include "typetraits.h"

// PrintF formatting for the guid when it's converted to and from a string
#define RED_RUID_STRING_FORMAT		( "%016llX" )

// Includes the null terminator for char buffer sizes
#define RED_RUID_STRING_BUFFER_SIZE	( 16 + 1 )

// Forward declares for friends
namespace tools
{
	class RUIDGenerator;
}
namespace serialization { namespace prv {
	class SerializeRUIDHelper;
}}

namespace red
{
	class PackageRUIDSerializer;
}

namespace red
{

// A cross-reference to a RUID value. A separate type for editor support and semantics.
// E.g., a RUIDRef implies there exists a RUID of the same value or else it's a broken reference.
// Could also be useful in situations where dumping RUIDs to ensure there are no duplicates anywhere from copying, but it's
// permitted for the RUID value to be cross-referenced elsewhere.
class RUIDRef;

// "RED Unique ID" or RUID.
//
// Static RUIDs are a lightweight ID that's meant to be unique within the studio (like a small GUID), and be persistable.
// It's generated by the editor backend to help ensure this uniqueness. It's good for about 34 years from now, so into the year 2050.
// See tools::RUIDGenerator to create during asset creation.
//
// Virtual RUIDs are created in the editor backend as well and typically represent placeholder RUIDs. E.g., virtual RUIDs in a prefab template,
// and then non-virtual RUIDs in a placed instance of the prefab. Otherwise they have the same characterisitcs as a static RUID.
// They should not be present at game runtime or they will fatal assert.
//
// Transient RUIDs can be created at game runtime for dynamic IDs unique to the current process, but should not be persisted in any way -
// it will result in a fatal assert.
class REDSYSTEM_API RUID
{
public:
 	RUID( const RUID& other ) = default;
 	RUID& operator=( const RUID& rhs ) = default;
	~RUID() = default;

	static RUID Zero();

	RED_FORCE_INLINE RUID( RUID&& other );
	RED_FORCE_INLINE RUID& operator=( RUID&& rhs );
	RED_FORCE_INLINE RUID(); // create a default zero RUID

	RED_FORCE_INLINE Bool operator<( RUID rhs ) const;
	RED_FORCE_INLINE Bool operator==( RUID rhs ) const;
	RED_FORCE_INLINE Bool operator!=( RUID rhs ) const;

	RED_FORCE_INLINE Uint32 CalcHash() const;
	RED_FORCE_INLINE Bool IsZero() const; // zero is never a valid RUID
	RED_FORCE_INLINE Bool IsStatic() const;
	RED_FORCE_INLINE Bool IsTransient() const;
	RED_FORCE_INLINE Bool IsVirtual() const;

	// Create a RUID from a hex string
	Bool FromString( const char* str );
	Bool Unsafe_FromString( const char* str ); // ctremblay: do not validate that string end with \0.

	// Writes a RUID out as a hex string
	void ToString( char* buffer, Uint32 bufferSize, const char* customFormat = nullptr ) const;

	// Create a transient RUID
	static RUID CreateTransient();

	// Disables virtual RUID support. Any attempt to create (or serialize) one will result in a fatal assert.
	// Expected to be called from the game engine.
	static void DisableVirtualRUIDs();

private:
	static constexpr Uint64 c_transientMask = RED_FLAG64(0);
	static constexpr Uint64 c_virtualMask = RED_FLAG64(1);

	friend class RUIDRef;
	friend class tools::RUIDGenerator;
	friend class serialization::prv::SerializeRUIDHelper;
	friend class PackageRUIDSerializer;
	RED_FORCE_INLINE explicit RUID( Uint64 value );
	RED_FORCE_INLINE void checkValue();

	enum ETransient{ Transient };
	explicit RUID( ETransient );
	RED_FORCE_INLINE RUID( EUndefined );

	// Hidden value; do not expose except for serialization or debug purposes, where it can be legally obtained through reinterpret_cast.
	// Don't want it to start getting externally stored in a Uint64 and lose sight that it's basically a small GUID.
	// A reinterpret_cast is valid as the first non-static member in a standard layout class.
	Uint64 m_value;
	static red::Atomic<Uint64> s_dynamicCounter;
	static Bool s_isVirtualRUIDsEnabled;
};

///---

class REDSYSTEM_API RUIDRef
{
	friend class serialization::prv::SerializeRUIDHelper;

public:
	RED_FORCE_INLINE RUIDRef(); // creates a reference to a zero RUID
	RED_FORCE_INLINE RUIDRef( RUID ruid ); // non-explicit to allow for easier operator conversions
	RUIDRef( const RUIDRef& other ) = default;
	RUIDRef& operator=( const RUIDRef& rhs ) = default;
	~RUIDRef() = default;
	RUIDRef( RUIDRef&& other ) = default;
	RUIDRef& operator=( RUIDRef&& rhs ) = default;

	static RUIDRef Zero();

	RED_FORCE_INLINE explicit operator RUID() const;

	RED_FORCE_INLINE Bool friend operator<( RUIDRef lhs, RUIDRef rhs );
	RED_FORCE_INLINE Bool friend operator==( RUIDRef lhs, RUIDRef rhs );
	RED_FORCE_INLINE Bool friend operator!=( RUIDRef lhs, RUIDRef rhs );
	RED_FORCE_INLINE Uint32 CalcHash() const;
	RED_FORCE_INLINE Bool IsZero() const; // zero is never a valid RUID
	RED_FORCE_INLINE Bool IsStatic() const;
	RED_FORCE_INLINE Bool IsTransient() const;
	RED_FORCE_INLINE Bool IsVirtual() const;

	// Create a RUID from a hex string
	RED_FORCE_INLINE Bool FromString( const char* str );

	// Writes a RUID out as a hex string
	RED_FORCE_INLINE void ToString( char* buffer, Uint32 bufferSize, const char* customFormat = nullptr ) const;

private:
	RUID m_ruid;
};

static_assert( sizeof( RUID ) == sizeof( Uint64 ), "RUID size should be 64-bits exactly" );
static_assert( sizeof( RUIDRef ) == sizeof( RUID ), "RUIDRef size should be same as RUID" );
static_assert( std::is_standard_layout<RUID>::value, "RUID should be standard layout (allowed to reinterpret cast to m_value)" );

}

RED_ALLOW_TYPE_AS_POD(red::RUID);

#include "ruid.inl"
